#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 times
x=0
while [ $x -le 19 ]
do
 echo "$x"
 case $x in
      "4") echo "bad luck from China";;
      "9") echo "bad luck from Japan";;
      "17") echo "bad luck from Italy";;
      esac
      ((x++))
done